### ISSUE TITLE
Custom font not loaded/working using WeasyTemplateResponseMixin for PDF creation

### ISSUE THREAD

**Issue by GitRon** [fdemmer/django-weasyprint#61]
Hi there,

I am using the `WeasyTemplateResponseMixin` and trying to get a custom font to load. The font files are located in my django statics dir.

Here's my code:

SCSS:  
```scss
$karla-font: MyFont, Arial, Helvetica, sans-serif;

@font-face {
  font-family: "MyFont";
  src: url('/static/fonts/MyFont-Regular.ttf') format("truetype"),
  url('/static/fonts/MyFont-Regular.otf') format("opentype");
}


body {
  font-family: $karla-font;
}
```

View:  

```python
class GeneratePdfView(WeasyTemplateResponseMixin, TemplateView):
    template_name = "my_template.html"
    pdf_filename = "my-export.pdf"
    valid_form = None

    def post(self, request, form, *args, **kwargs):
        self.valid_form = form
        return super().get(request, form, *args, **kwargs)

    def get_pdf_stylesheets(self):
        return [Path(Path(settings.APPS_DIR).as_posix() + '/static/scss/pdf/my-styles.css').as_posix()]

    ...
```

Hints:  
* The rest of the styles are being loaded correctly. 
* The url resolver does not try to load the fonts, only the images within the template
* I tried prefixing the url to the fonts with `file:`
* I tried a relative path

Any ideas what I might be doing wrong? Unfortunately this feature is not covered in the docs AFAIK 😕 

Thx!
Ronny
